### ISSUE TITLE
python 2.7 compatibility

### ISSUE THREAD

**Issue by anandkoirala** [philipperemy/keract#28]
import keract
  File "/apps/software/python/python-2.7.15/lib/python2.7/site-packages/keract/__init__.py", line 1, in <module>
    from keract.keract import *
  File "/apps/software/python/python-2.7.15/lib/python2.7/site-packages/keract/keract.py", line 5
    def _evaluate(model: Model, nodes_to_evaluate, x, y=None):
                                    ^
SyntaxError: invalid syntax

**Comment by anandkoirala** [comment]
@philipperemy  can you please tell me why am i getting syntax error on model:Model definition?
i am on python 2.7.15

**Comment by philipperemy** [comment]
Hum can you try python 3+? @anandkoirala

**Comment by anandkoirala** [comment]
Hi, @philipperemy  it seemed working on python 3.5.2 on other computer.  but i can only run 2.7 on my computer because of compatibility issues with other programs.. is there any quick fix?
 I have a 'Xception' model trained with two input images (2 inputs). this is a Siamese network. i wanted to visualize the activation on the last layer. is your program ready to do this?  
i tried to run some program by typing python heatmap.py
 but it says     if not model._is_compiled:
AttributeError: 'Model' object has no attribute '_is_compiled'
can you provide the usage command on the files or at least for my 'Xception' Siamese network.
Regards,
Anand

**Comment by philipperemy** [comment]
@anandkoirala for now only the compatibility with python 3.5 is ensured. It's not likely to work with python 2.7. There's no plan at the moment to make it compatible with python 2.7.
